services:
  - type: web
    name: selectra-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GEMINI_API_KEYS
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: DEEPGRAM_KEY
        sync: false
      - key: OPENAI_COMPATIBLE_KEY
        sync: false
